config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }, skip: [:registrations]
  devise_scope :user do
    # edit, destroy を除外
    resource :registration,
             only: %i[new create update],
             controller: 'users/registrations',
             path: 'users',
             as: :user_registration,
             path_names: { new: 'sign_up' } do
      get :cancel, on: :collection
    end
    get 'users/profile',  to: 'users/registrations#profile',  as: :edit_user_profile
    get 'users/password', to: 'users/registrations#password', as: :edit_user_password
  end

  devise_for :moderators, controllers: {
    sessions: 'moderators/sessions',
    registrations: 'moderators/registrations'
  }, skip: [:registrations], path: 'moderators', path_names: { sign_in: 'sign_in', sign_out: 'sign_out' }
  devise_scope :moderator do
    resource :registration,
             only: %i[update],
             controller: 'moderators/registrations',
             path: 'moderators',
             as: :moderator_registration
    get 'moderators/profile',  to: 'moderators/registrations#profile',  as: :edit_moderator_profile
    get 'moderators/password', to: 'moderators/registrations#password', as: :edit_moderator_password
  end

  resources :topics, except: %i[destroy] do
    resources :comments, only: %i[create edit update]
  end

  resources :comments, only: %i[] do
    resources :histories, controller: 'comment_histories', only: %i[index] do
      get 'compare', on: :collection
    end
  end

  resources :reports, only: %i[index new create]
  resources :decisions, only: %i[index new create]

  namespace :my do
    resources :invitations, only: %i[index] do
      member do
        get :accept
        post :accept, action: :create_acceptance
        post :reject
      end
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  root to: 'tenants#index'
  scope '/:tenant_slug', as: :tenant do
    get '/', to: 'tenants#show', as: :root

    get 'profile', to: 'tenant_profiles#edit', as: :users_profile
    patch 'profile', to: 'tenant_profiles#update'

    scope module: 'tenants' do
      resources :users, only: %i[show]
      resources :invitations, only: %i[new create]
    end
  end
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id                       :bigint           not null, primary key
#  content                  :text(65535)      not null
#  current_version_no       :integer          not null
#  hidden                   :boolean          default(FALSE), not null
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  author_id                :bigint           not null
#  hidden_cause_decision_id :bigint
#  topic_id                 :bigint           not null
#
# Indexes
#
#  idx_comments_author_id            (author_id)
#  idx_comments_topic_id_created_at  (topic_id,created_at)
#
# Foreign Keys
#
#  fk_rails_...  (author_id => users.id)
#  fk_rails_...  (topic_id => topics.id)
#
class Comment < ApplicationRecord
  include Reportable
  include CommentSharedBehavior

  belongs_to :hidden_cause_decision, class_name: 'Decision', optional: true
  has_many :histories, class_name: 'CommentHistory', dependent: :restrict_with_error

  validates :current_version_no, presence: true, numericality: { only_integer: true, greater_than: 0 }

  counter_culture :topic, column_name: 'total_comment'

  before_validation :set_initial_version, on: :create
  after_create :create_history

  def update_content!(content)
    return if will_save_change_to_content?

    with_lock do
      next_version_no = current_version_no + 1
      update!(content: content, current_version_no: next_version_no)
      histories.create!(
        topic: topic,
        author: author,
        content: content,
        version_no: next_version_no
      )
    end
  end

  def apply_decision!(decision)
    hide_by_decision!(decision)
  end

  def hide_by_decision!(decision)
    update!(
      hidden: true,
      hidden_cause_decision: decision
    )
  end

  def invisible?
    hidden? || author.suspended?
  end

  private

  def set_initial_version
    self.current_version_no ||= 1
  end

  def create_history
    histories.create!(
      topic: topic,
      author: author,
      content: content,
      version_no: current_version_no
    )
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_topic, only: %i[create edit update]
  before_action :set_comment, only: %i[edit update]
  before_action -> { authorize_action!(@comment) }

  def edit; end

  def create
    @comment = Comment.create!(
      topic: @topic,
      author: current_user,
      **comment_params
    )

    redirect_to @topic, notice: t('flash.actions.comment_created.notice')
  rescue ActiveRecord::RecordInvalid => e
    @comment = e.record
    set_pagination

    respond_to do |format|
      format.turbo_stream do
        render :create_error, status: :unprocessable_content
      end
    end
  end

  def update
    @comment.update_content!(comment_params[:content])
    redirect_to comment_histories_path(@comment),
                notice: t('flash.actions.update.notice', resource: Comment.model_name.human)
  rescue ActiveRecord::RecordInvalid => e
    @comment = e.record
    render :edit, status: :unprocessable_content
  end

  private

  def comment_params
    params.expect(comment: [:content])
  end

  def set_pagination
    @pagination = Pagination::Paginator.new(
      relation: @topic.comments, page: params[:page], per: params[:per]
    ).call
  end

  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <div class="comment-header">
    <p><strong><%= comment.author.nickname %></strong></p>
  </div>
  <%= render_comment_content(comment) %>
  <div class="comment-footer">
    <p>
      <%= t('created_at') %> <%= l(comment.created_at, format: :default) %>
    </p>
    <div class="comment-actions">
      <% if can_access?('comments', 'edit', comment) %>
        <p>
          <span class="material-icons">edit</span>
          <%= link_to t('edit'), edit_topic_comment_path(comment.topic, comment), class: "edit-link" %>
        </p>
      <% end %>
      <% if can_access?('comment_histories', 'index', comment) %>
        <p>
          <span class="material-icons">history</span>
          <%= link_to t('history'), comment_histories_path(comment), class: "history-link" %>
        </p>
      <% end %>
      <% if !comment.invisible? && can_access?('reports', 'new', comment) %>
        <p>
          <span class="material-icons">flag</span>
          <%= link_to t('.report_user'), new_report_path(
            format: :turbo_stream,
            reportable_type: "user",
            reportable_id: comment.author.id,
            from_topic_id: comment.topic.id,
          ), data: { turbo_prefetch: false } %>
        </p>
        <p>
          <span class="material-icons">flag</span>
          <%= link_to t('.hide_comment'), new_report_path(
            format: :turbo_stream,
            reportable_type: "comment",
            reportable_id: comment.id,
            from_topic_id: comment.topic.id,
          ), data: { turbo_prefetch: false } %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/create_error.turbo_stream.erb
<%= turbo_stream.update "comment-form-errors" do %>
  <%= render partial: "shared/form_errors", locals: { model: @comment } %>
<% end %>

app/views/comments/edit.html.erb
<section class="form-card">
  <%= render 'shared/back_button', url: topic_path(@topic) %>
  <h3><%= t('edit', resource: Comment.model_name.human) %></h3>

  <%= form_with(model: [@topic, @comment], local: true) do |f| %>
    <%= render partial: "shared/form_errors", locals: { model: @comment } %>

    <div class="field">
      <%= f.label :content %>
      <%= f.text_area :content, rows: 5 %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</section>