config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }, skip: [:registrations]
  devise_scope :user do
    # edit, destroy を除外
    resource :registration,
             only: %i[new create update],
             controller: 'users/registrations',
             path: 'users',
             as: :user_registration,
             path_names: { new: 'sign_up' } do
      get :cancel, on: :collection
    end
    get 'users/profile',  to: 'users/registrations#profile',  as: :edit_user_profile
    get 'users/password', to: 'users/registrations#password', as: :edit_user_password
  end

  devise_for :moderators, controllers: {
    sessions: 'moderators/sessions',
    registrations: 'moderators/registrations'
  }, skip: [:registrations], path: 'moderators', path_names: { sign_in: 'sign_in', sign_out: 'sign_out' }
  devise_scope :moderator do
    resource :registration,
             only: %i[update],
             controller: 'moderators/registrations',
             path: 'moderators',
             as: :moderator_registration
    get 'moderators/profile',  to: 'moderators/registrations#profile',  as: :edit_moderator_profile
    get 'moderators/password', to: 'moderators/registrations#password', as: :edit_moderator_password
  end

  resources :topics, except: %i[destroy] do
    resources :comments, only: %i[create edit update]
  end

  resources :comments, only: %i[] do
    resources :histories, controller: 'comment_histories', only: %i[index] do
      get 'compare', on: :collection
    end
  end

  resources :reports, only: %i[index new create]
  resources :decisions, only: %i[index new create]

  namespace :my do
    resources :invitations, only: %i[index] do
      member do
        get :accept
        post :accept, action: :create_acceptance
        post :reject
      end
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  root to: 'tenants#index'
  scope '/:tenant_slug', as: :tenant do
    get '/', to: 'tenants#show', as: :root

    get 'profile', to: 'tenant_profiles#edit', as: :users_profile
    patch 'profile', to: 'tenant_profiles#update'

    scope module: 'tenants' do
      resources :users, only: %i[show]
      resources :invitations, only: %i[new create]
    end
  end
end

app/models/topic.rb
# frozen_string_literal: true

# トピックモデル
# 掲示板に集まって人で話し合うためのテーマやトピックのこと
# == Schema Information
#
# Table name: topics
#
#  id            :bigint           not null, primary key
#  title         :string(255)      not null
#  total_comment :integer          default(0), not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  author_id     :bigint           not null
#
# Indexes
#
#  idx_topics_author_id   (author_id)
#  idx_topics_created_at  (created_at)
#
# Foreign Keys
#
#  fk_rails_...  (author_id => users.id)
#
class Topic < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :restrict_with_exception, inverse_of: :topic
  validates :title, length: { minimum: 1, maximum: 120 }, no_html: true
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  before_action :set_topic, only: %i[show edit update]
  before_action -> { authorize_action!(@topic) }

  def index
    @pagination = Pagination::Paginator.new(
      relation: topics, page: params[:page], per: params[:per]
    ).call

    redirect_to topics_path, alert: t('flash.actions.out_of_bounds') if @pagination.out_of_bounds
  end

  def show
    @pagination = Pagination::Paginator.new(
      relation: comments, page: params[:page], per: params[:per]
    ).call

    redirect_to topic_path(@topic), alert: t('flash.actions.out_of_bounds') if @pagination.out_of_bounds
  end

  def new
    @topic = Topic.new
  end

  def edit; end

  def create
    @topic = current_user.topics.build(topic_params)
    if @topic.save
      redirect_to @topic, notice: t('flash.actions.create.notice', resource: Topic.model_name.human)
    else
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: t('flash.actions.update.notice', resource: Topic.model_name.human)
    else
      render :edit, status: :unprocessable_content
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.expect(topic: [:title])
  end

  def topics
    Topic
      .order(created_at: :desc, id: :desc)
      .eager_load(:author)
  end

  def comments
    @topic.comments.eager_load(:author).order(created_at: :desc)
  end
end

app/views/topics/_edit_action.html.erb
<% if can_access?('topics', 'edit', topic) %>
    <div class="edit-actions">
        <%= link_to edit_topic_path(topic) do %>
            <span class="material-icons">edit</span>
        <% end %>
    </div>
<% end %>

app/views/topics/_form.html.erb
<article class="layout-center">
  <section class="form-card">
    <%= render 'shared/back_button', url: topics_path %>
    <h2><%= t("title.#{topic.new_record? ? 'new' : 'edit'}", resource: Topic.model_name.human) %></h2>

    <%= form_with model: topic do |f| %>
      <%= render partial: "shared/form_errors", locals: { model: topic } %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </section>
</article>

app/views/topics/_item.html.erb
<li class="topic-item">
    <div>
        <%= link_to topic_path(topic) do %>
            <h3><%= topic.title %></h3>
        <% end %>
        <div class="topic-details">
            <p><%= t('author') %> <%= topic.author.nickname %></p>
            <p><%= t('created_at') %> <%= l(topic.created_at, format: :default) %></p>
            <p><%= t('comment_count') %> <%= topic.total_comment %><%= t('.count_suffix') %></p>
        </div>
    </div>
    <%= render partial: 'edit_action', locals: { topic: topic } %>
</li>

app/views/topics/edit.html.erb
<%= render 'form', topic: @topic %>

app/views/topics/index.html.erb
<article>
  <div class="topic-header">
    <h2><%= t('title.index', resource: Topic.model_name.human) %></h2>
    <div class="topic-actions">
      <% if can_access?('topics', 'new') %>
        <%= link_to new_topic_path do %>
          <%= t('.action.new', resource: Topic.model_name.human) %>
        <% end %>
      <% end %>
    </div>
  </div>
  <ul class="topics-list">
    <%= render partial: 'item', collection: @pagination.records, as: :topic %>
  </ul>
  <%= render partial: 'shared/pagination', locals: { pagination: @pagination } %>
</article>

app/views/topics/new.html.erb
<%= render 'form', topic: @topic %>

app/views/topics/show.html.erb
<article>
  <%= render 'shared/back_button', url: topics_path %>
  <section class="topic-show">
    <h3><%= @topic.title %></h3>
    <div class="topic-details">
      <p><%= t('author') %> <%= @topic.author.nickname %></p>
      <p><%= t('created_at') %> <%= l(@topic.created_at, format: :default) %></p>
      <p><%= t('comment_count') %> <%= @topic.total_comment %><%= t('.count_suffix') %></p>
    </div>
    <%= render partial: 'edit_action', locals: { topic: @topic } %>
  </section>
  <% if @pagination.records.any? %>
    <section class="topic-comments">
      <h4><%= t('.comment') %></h4>
      <div id="comment-list" class="comment-list">
        <%= render partial: 'comments/comment', collection: @pagination.records.to_a.reverse %>
      </div>
      <%= render partial: 'shared/pagination', locals: { pagination: @pagination } %>
    </section>
  <% end %>
  <% if can_access?('comments', 'create') %>
    <section class="form-card">
      <h3><%= t('.new_comment') %></h3>
      <div id="comment-form-errors"></div>
      <%= form_with(model: [@topic, Comment.new], local: false) do |f| %>
        <div class="field">
          <%= f.label :content %>
          <%= f.text_area :content, rows: 5 %>
        </div>
        <div class="actions">
          <%= f.submit t('.create') %>
        </div>
      <% end %>
    </section>
  <% end %>
</article>