config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }, skip: [:registrations]
  devise_scope :user do
    # edit, destroy を除外
    resource :registration,
             only: %i[new create update],
             controller: 'users/registrations',
             path: 'users',
             as: :user_registration,
             path_names: { new: 'sign_up' } do
      get :cancel, on: :collection
    end
    get 'users/profile',  to: 'users/registrations#profile',  as: :edit_user_profile
    get 'users/password', to: 'users/registrations#password', as: :edit_user_password
  end

  devise_for :moderators, controllers: {
    sessions: 'moderators/sessions',
    registrations: 'moderators/registrations'
  }, skip: [:registrations], path: 'moderators', path_names: { sign_in: 'sign_in', sign_out: 'sign_out' }
  devise_scope :moderator do
    resource :registration,
             only: %i[update],
             controller: 'moderators/registrations',
             path: 'moderators',
             as: :moderator_registration
    get 'moderators/profile',  to: 'moderators/registrations#profile',  as: :edit_moderator_profile
    get 'moderators/password', to: 'moderators/registrations#password', as: :edit_moderator_password
  end

  resources :topics, except: %i[destroy] do
    resources :comments, only: %i[create edit update]
  end

  resources :comments, only: %i[] do
    resources :histories, controller: 'comment_histories', only: %i[index] do
      get 'compare', on: :collection
    end
  end

  resources :reports, only: %i[index new create]
  resources :decisions, only: %i[index new create]

  namespace :my do
    resources :invitations, only: %i[index] do
      member do
        get :accept
        post :accept, action: :create_acceptance
        post :reject
      end
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  root to: 'tenants#index'
  scope '/:tenant_slug', as: :tenant do
    get '/', to: 'tenants#show', as: :root

    get 'profile', to: 'tenant_profiles#edit', as: :users_profile
    patch 'profile', to: 'tenant_profiles#update'

    scope module: 'tenants' do
      resources :users, only: %i[show]
      resources :invitations, only: %i[new create]
    end
  end
end

app/views/shared/_back_button.html.erb
<div class="back-button-container">
  <%= link_to url, class: "back-button" do %>
    <span class="material-icons">arrow_back</span>
  <% end %>
</div>

app/views/shared/_flash_messages.html.erb
<div class="flash-messages" id="flash-messages">
  <% flash.each do |type, message| %>
    <div class="flash-message flash-<%= type %>" data-controller="flash">
      <span class="flash-icon material-icons">
        <% if type == "notice" %>
          check_circle
        <% elsif type == "alert" %>
          error
        <% elsif type == "warning" %>
          warning
        <% end %>
      </span>
      <span class="flash-content"><%= message %></span>
      <button class="flash-close" data-action="click->flash#close">
        <span class="material-icons">close</span>
      </button>
    </div>
  <% end %>
</div>

app/views/shared/_form_errors.html.erb
<% if model.errors.any? %>
  <div class="form-error-messages">
    <div class="form-error-icon">
      <span class="material-icons">error</span>
    </div>
    <div class="form-error-content">
      <h3>
        <%= I18n.t("errors.messages.not_saved",
                   count: model.errors.count,
                   resource: model.class.model_name.human.downcase) %>
      </h3>
      <ul>
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
    <div class="header-left">
        <%= link_to t('application_title'), current_moderator ? reports_path : root_path, class: "logo" %>
    </div>
    <div class="header-right dropdown" data-controller="dropdown">
        <% if only_user_signed_in? %>
            <button class="dropdown-trigger" data-action="click->dropdown#toggle">
                <span class="material-icons user-icon">account_circle</span>
                <span class="material-icons">expand_more</span>
            </button>
            <div class="dropdown-menu" data-dropdown-target="menu">
                <ul class="dropdown-list">
                    <li class="dropdown-item">
                        <%= link_to edit_user_profile_path do %>
                            <span class="material-icons">edit</span>
                            <span class="vertical-middle"><%= t('header.profile') %></span>
                        <% end %>
                    </li>
                    <li class="dropdown-item">
                        <%= link_to edit_user_password_path do %>
                            <span class="material-icons">lock</span>
                            <span class="vertical-middle"><%= t('header.password') %></span>
                        <% end %>
                    </li>
                    <li class="dropdown-item">
                        <%= button_to destroy_user_session_path, method: :delete, class: "logout" do %>
                            <span class="material-icons">logout</span>
                            <span class="vertical-middle"><%= t('header.logout') %></span>
                        <% end %>
                    </li>
                </ul>
            </div>
        <% elsif moderator_signed_in? %>
            <div class="header-nav">
                <%= link_to reports_path, class: "nav-button #{'active' if controller_name == 'reports'}" do %>
                    <span class="material-icons">report</span>
                    <%= t('title.index', resource: Report.model_name.human) %>
                <% end %>
                <%= link_to decisions_path, class: "nav-button #{'active' if controller_name == 'decisions'}" do %>
                    <span class="material-icons">gavel</span>
                    <%= t('title.index', resource: Decision.model_name.human) %>
                <% end %>
            </div>
            <button class="dropdown-trigger" data-action="click->dropdown#toggle">
                <span class="material-icons user-icon">admin_panel_settings</span>
                <span class="material-icons">expand_more</span>
            </button>
            <div class="dropdown-menu" data-dropdown-target="menu">
                <ul class="dropdown-list">
                    <li class="dropdown-item">
                        <%= link_to edit_moderator_profile_path do %>
                            <span class="material-icons">edit</span>
                            <span class="vertical-middle"><%= t('header.profile') %></span>
                        <% end %>
                    </li>
                    <li class="dropdown-item">
                        <%= link_to edit_moderator_password_path do %>
                            <span class="material-icons">lock</span>
                            <span class="vertical-middle"><%= t('header.password') %></span>
                        <% end %>
                    </li>
                    <li class="dropdown-item">
                        <%= button_to destroy_moderator_session_path, method: :delete, class: "logout" do %>
                            <span class="material-icons">logout</span>
                            <%= t('header.logout') %>
                        <% end %>
                    </li>
                </ul>
            </div>
        <% else %>
            <div class="header-nav">
                <%= link_to new_user_registration_path, class: "nav-button" do %>
                <span class="material-icons">person_add</span>
                <%= t('authentication.signup') %>
                <% end %>
                <%= link_to new_user_session_path, class: "nav-button" do %>
                <span class="material-icons">login</span>
                <%= t('authentication.login') %>
                <% end %>
            </div>
        <% end %>
    </div>
</header>

app/views/shared/_invitation_banner.html.erb
<% if user_signed_in? && current_user.pending_invitations? && request.path != my_invitations_path %>
  <div class="invitation-banner">
    <%= link_to my_invitations_path, class: "invitation-banner-link" do %>
      <span class="invitation-banner-text">
        <%= t('.message', count: pending_invitations_count) %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/shared/_pagination.html.erb
<% unless @pagination.page == 1 and @pagination.ahead == 0 %>
  <nav class="pagination">
    <% @pagination.window_numbers.each do |num| %>
      <% if num == @pagination.page %>
        <span class="is-current"><%= num %></span>
      <% else %>
        <%= link_to num, @pagination.page_path(
          base_path: request.path,
          page_num: num,
          query_params: local_assigns.fetch(:query_params, {})
        ) %>
      <% end %>
    <% end %>
  </nav>
<% end %>